export const flipCardStyles = {
  flipCard: {
    backgroundColor: 'transparent',
    perspective: '1000px',
    cursor: 'pointer',
    height: '100%',
    width: '100%',
    position: 'relative' as const,
  },
  flipCardInner: {
    position: 'relative' as const,
    width: '100%',
    height: '100%',
    textAlign: 'center' as const,
    transition: 'transform 0.6s',
    transformStyle: 'preserve-3d' as const,
    boxShadow: '0 4px 8px 0 rgba(0,0,0,0.2)',
  },
  flipCardInnerFlipped: {
    transform: 'rotateY(180deg)',
  },
  flipCardFront: {
    position: 'absolute' as const,
    width: '100%',
    height: '100%',
    WebkitBackfaceVisibility: 'hidden' as const,
    backfaceVisibility: 'hidden' as const,
    borderRadius: '8px',
    display: 'flex',
    flexDirection: 'column' as const,
    justifyContent: 'center',
    alignItems: 'center',
    padding: '1.5rem',
    backgroundColor: '#f8f8f8',
    color: '#333',
  },
  flipCardBack: {
    position: 'absolute' as const,
    width: '100%',
    height: '100%',
    WebkitBackfaceVisibility: 'hidden' as const,
    backfaceVisibility: 'hidden' as const,
    borderRadius: '8px',
    display: 'flex',
    flexDirection: 'column' as const,
    justifyContent: 'center',
    alignItems: 'center',
    padding: '1.5rem',
    backgroundColor: '#4a6cf7',
    color: 'white',
    transform: 'rotateY(180deg)',
  },
  certificationCard: {
    height: '220px',
    marginBottom: '20px',
  },
  achievementCard: {
    height: '200px',
    marginBottom: '20px',
  },
  certificateImage: {
    maxWidth: '100%',
    maxHeight: '120px',
    objectFit: 'contain' as const,
  },
  certificateLink: {
    marginTop: '10px',
    color: 'white',
    textDecoration: 'underline',
  },
};